version: '3'

services:
  nginx:
    container_name: 'nginx_jenkins_proxy'
    image: nginx:1.17.2
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/jenkins.conf
      - ./jenkins_home:/var/lib/jenkins_home/ #war folder
      - ./jenkins_home/userContent:/var/lib/jenkins/ #jenkins home folder
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker:ro
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
  jenkins:
    container_name: 'jenkins_server'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${JENKINS_PORT}:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
